# Let's prep our data

### Get the data

- Download to your computer <a href="https://drive.google.com/file/d/1-798fq909hN3x3UxBYUDZrkEaPTliyvJ/view?usp=sharing"> this 256MB file</a> that contains NYPD summons data from 2015-2025s.

## 2020 NYC population by borough
```python
populations = {
    "BROOKLYN": 2736074,
    "QUEENS": 2405464,
    "MANHATTAN": 1694251,
    "BRONX": 1472654,
    "STATEN ISLAND": 495747
}
```

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("summons-15-25.csv")

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384334 entries, 0 to 1384333
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   SUMMONS_KEY            1384334 non-null  int64
 1   SUMMONS_DATE           1384334 non-null  str
 2   OFFENSE_DESCRIPTION    1384316 non-null  str
 3   LAW_SECTION_NUMBER     1348831 non-null  str
 4   LAW_DESCRIPTION        1309406 non-null  str
 5   SUMMONS_CATEGORY_TYPE  1309321 non-null  str
 6   AGE_GROUP              1354372 non-null  str
 7   SEX                    1284382 non-null  str
 8   RACE                   964769 non-null   str
 9   JURISDICTION_CODE      1384334 non-null  int64
 10  BORO                   1372084 non-null  str
 11  PRECINCT_OF_OCCUR      1384334 non-null  int64
 12  X_COORDINATE_CD        1383871 non-null  float64
 13  Y_COORDINATE_CD        1383871 non-null  float64
 14  Latitude               1383870 non-null  float64
 15  Longitude              1383870 non-null  float64
 16  Lon_Lat                1383870 non-null  str
 17  YEAR                   1384334 non-null  int64
dtypes: float64(4), int64(4), str(10)
memory usage: 190.1 MB

In [8]:
## read the file
## import
## name the df summons_df

summons_df = pd.read_csv("summons-15-25.csv")

In [9]:
(summons_df)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384329,140411914,2015-01-01,LITTERING,16-118,Administrative Code,LITTERING,45-64,M,UNKNOWN,0,BROOKLYN,70,995708.0,176233.0,40.650396,-73.958709,POINT (-73.95870942899995 40.65039633400005),2015
1384330,140463604,2015-01-01,"MARIJUANA, POSSESSION OF",221.05,Penal Law,MARIJUANA,25-44,M,UNKNOWN,0,BRONX,44,1008656.0,245335.0,40.840038,-73.911797,POINT (-73.91179707599997 40.84003765600005),2015
1384331,140424873,2015-01-01,OTHER ADMIN CODE,9999,Administrative Code,OTHER ADMIN CODE,NaN,D,UNKNOWN,0,MANHATTAN,7,987559.0,201831.0,40.720664,-73.988064,POINT (-73.98806399499993 40.72066379300003),2015
1384332,140418300,2015-01-01,AFTER HOURS CONSUMPTION,106-5,ABC,ABC,45-64,M,UNKNOWN,0,BROOKLYN,67,1003469.0,171347.0,40.636972,-73.930754,POINT (-73.93075448599996 40.63697187500002),2015
1384333,140418234,2015-01-01,DISCON: REFUSE LAWFUL ORDER,240.20-6,Penal Law,DISORDERLY CONDUCT,<18,M,UNKNOWN,0,BRONX,41,1015630.0,236919.0,40.816916,-73.886632,POINT (-73.88663211599999 40.81691612900005),2015

In [10]:
summons_df.head(10)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024
5,298704180,2024-12-31,POSS. OF MACE,10-131,Administrative Code,AIR GUN,25-44,F,BLACK,0,STATEN ISLAND,120,962004.0,164939.0,40.619379,-74.080130,POINT (-74.08013 40.619379),2024
6,298702245,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,M,WHITE,0,BROOKLYN,61,996615.0,161248.0,40.609266,-73.955467,POINT (-73.955467 40.609266),2024
7,298697783,2024-12-31,CONSUMPTION OF ALCOHOL IN VEHICLE,1227,VTL,VTL,18-24,M,WHITE HISPANIC,0,BROOKLYN,70,995870.0,175002.0,40.647019,-73.958125,POINT (-73.958125 40.647019),2024
8,298706343,2024-12-31,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),18-24,M,BLACK,0,BRONX,40,1007923.0,237493.0,40.818507,-73.914472,POINT (-73.91447241436298 40.81850733182842),2024
9,298704196,2024-12-31,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),18-24,M,BLACK,0,BROOKLYN,75,1013888.0,179945.0,40.660544,-73.893174,POINT (-73.893174 40.660544),2024

In [12]:
summons_df["OFFENSE_DESCRIPTION"]

0                        DISORDERLY CONDUCT
1                           IMPROPER PLATES
2                                  TRESPASS
3             FEDERAL MOTOR VEH. SAFETY REG
4          POSSESSION OF ALCOHOL BY A MINOR
                         ...
1384329                           LITTERING
1384330            MARIJUANA, POSSESSION OF
1384331                    OTHER ADMIN CODE
1384332             AFTER HOURS CONSUMPTION
1384333         DISCON: REFUSE LAWFUL ORDER
Name: OFFENSE_DESCRIPTION, Length: 1384334, dtype: str

In [33]:
# -----------------------------
# 1) Load and clean the dataset
# -----------------------------
# Update path if needed
df = pd.read_csv("summons-15-25.csv")

# Replace common missing-value markers with pandas missing value
df = df.replace({"": pd.NA, "(null)": pd.NA, "UNKNOWN": pd.NA})

# Normalize borough names
df["BORO_CLEAN"] = df["BORO"].str.upper()

# Ensure YEAR is numeric
df["YEAR"] = pd.to_numeric(df["YEAR"], errors="coerce")

# Clean sex values: keep only M/F, everything else -> missing
df["SEX_CLEAN"] = df["SEX"].str.upper()
df["SEX_CLEAN"] = df["SEX_CLEAN"].where(df["SEX_CLEAN"].isin(["M", "F"]), pd.NA)

# Clean race
df["RACE_CLEAN"] = df["RACE"].str.upper()

In [44]:
# ---------------------------------------
# Q1) Which borough had the most summons?
# ---------------------------------------
summons_by_boro = df["BORO_CLEAN"].value_counts().rename("summons_count")

top_borough = summons_by_boro.idxmax()
top_count = summons_by_boro.max()

print(f"Q1: {top_borough} had the most summons with {top_count:,} total.")

Q1: BROOKLYN had the most summons with 427,679 total.

In [46]:
# ----------------------------------------------------------------
# Q2) How many times did the top 10 most common offenses occur?
# ----------------------------------------------------------------

top_10_offenses = df["OFFENSE_DESCRIPTION"].value_counts().nlargest(10)

top_offense = top_10_offenses.idxmax()
top_offense_count = top_10_offenses.max()
top_10_total = top_10_offenses.sum()

print(
    f"\nQ2: The top 10 most common offenses occurred {top_10_total:,} times combined. "
    f"The #1 offense was '{top_offense}' with {top_offense_count:,} occurrences.\n"
    f"{top_10_offenses.to_string()}"
)

Q2: The top 10 most common offenses occurred 764,799 times combined. The #1 offense was 'CONSUMPTION OF ALCOHOL' with 248,650 occurrences.
OFFENSE_DESCRIPTION
CONSUMPTION OF ALCOHOL           248650
FEDERAL MOTOR VEH. SAFETY REG    158420
MARIJUANA, POSSESSION OF          84910
URINATING IN PUBLIC               50340
RECKLESS DRIVING                  44691
ALCOHOLIC BEVERAGE IN PUBLIC      43789
FAILURE TO COMPLY WITH SIGN       42810
TRESPASS                          38595
OTHER ADMIN CODE                  31851
DISORDERLY CONDUCT                20743

In [47]:
# ------------------------------------------------------
# Q3) Total number of summons broken down by year
# ------------------------------------------------------
summons_by_year = (
    df.dropna(subset=["YEAR"])
      .groupby(df["YEAR"].astype(int))
      .size()
      .rename("summons_count")
      .sort_index()
)

peak_year = summons_by_year.idxmax()
peak_count = summons_by_year.max()

print(
    f"\nQ3: {summons_by_year.sum():,} total summons were issued. "
    f"The peak year was {peak_year} with {peak_count:,} summons.\n"
    f"{summons_by_year.to_string()}"
)

Q3: 1,384,334 total summons were issued. The peak year was 2015 with 297,748 summons.
YEAR
2015    297748
2016    267950
2017    165093
2018     89895
2019     85899
2020     55589
2021     45717
2022     58059
2023    106529
2024     94542
2025    117313

In [48]:

# -----------------------------------------------------------------------------------
# Q4) Most unusual summons (rarest offense descriptions)
# -----------------------------------------------------------------------------------
offense_counts = df["OFFENSE_DESCRIPTION"].value_counts()

singletons = offense_counts[offense_counts == 1]
very_rare   = offense_counts[offense_counts <= 2].sort_values()

print(
    f"\nQ4: {len(singletons)} offense(s) appeared exactly once (rarest). "
    f"{len(very_rare)} offense(s) had 2 or fewer occurrences.\n"
    f"Singleton offenses:\n{singletons.to_string()}"
)

Q4: 52 offense(s) appeared exactly once (rarest). 79 offense(s) had 2 or fewer occurrences.
Singleton offenses:
OFFENSE_DESCRIPTION
RAILROAD TRACK, PLACE LESS THAN 5 FEET FROM                                         1
UNLICENSED HAIR/NAIL SALON                                                          1
HARASS/THREATEN/ABUSE; PASSENGER                                                    1
STREET; PLACE/PERMIT WITHOUT A PERMIT                                               1
VEHICLE REBUILDER FAILED TO KEEP PROPER RECORDS                                     1
DANGEROUS CONDITION; CREATE IN PARK/ROAD                                            1
DEFECTIVE DURING TRIP; FAIL TO NOTIFY PASSENGER                                     1
DENIAL OF LICENSE OR RENEWAL, SUSPENSION AND REVOCATION                             1
SKATEBOARD; OTHER THAN DESIGNATED AREA                                              1
SPRAY PAINT/BROAD TIPPED MARKER ON DISPLAY (NOT IN A LOCKED CASE)                   1
DISTRIBUTOR (TO VENDOR), UNLICENSED                                                 1
AUDIO EQUIPMENT; FAIL TO OBLIGE PASSENGER REGARDING ON/OFF/SELECTION                1
BICYCLE ON GRASS/BRIDLE PATH; RIDE ON                                               1
UNREASONABLE NOISE (FROM A MUSICAL INSTRUMENT)                                      1
SOLICIT PASSENGER; BY USE OF ANOTHER PERSON                                         1
COMMUNICATION SYSTEM, BASE; UNLICENSED                                              1
NO ""NO CHOKING"" SIGN IN FOOD ESTABLISHMENT                                        1
NO ""BILLIARD & POCKET-BILLIARD ROOM LICENSE""                                      1
UNLICENSED LOCKSMITH/KEY MAKER                                                      1
UNVACCINATED DOG                                                                    1
NO ""CERTIFICATE OF OCCUPANCY""                                                     1
NO WASHING FACILITY WITH RUNNING HOT OR COLD WATER                                  1
DRIVER DOES NOT POSSESS ""FOR HIRE-VEHICLE"" LICENSE                                1
UNLICENSED SIDEWALK CAF                                                             1
SOLICIT PASSENGER; WORDS OTHER THAN "TAXI", "CAB", OR "TAXICAB"                     1
VEHICLE DISMANTLER FAILED TO KEEP PROPER RECORDS                                    1
CART MAN, UNLICENSED                                                                1
NO SANITARY SOAP DISPENSER                                                          1
FAILURE TO NOTIFY A PRECINCT WITHIN 2 HOURS OF TOWING A VEHICLE WHEN OWNER IS UN    1
SALE BETWEEN 3AM-12PM ON SUNDAY                                                     1
DEFECTIVE; PICK-UP/TRANSPORT PASSENGERS WHEN                                        1
METER OPERATING; TAMPER WITH METER/SEALS/CONNECTION/WIRING/TIRES TO AFFECT          1
UNHYGIENIC USE OF THE FOUNTAIN OR POOL AREA                                         1
USED PAPER TOWELS/PAPER/OTHER MATERIALS NOT IN GARBAGE                              1
LOST/STOLEN; FAIL TO NOTIFY WITHIN 72 HOURS                                         1
OPENING ENTRIES; FAIL TO SIGN AND CERTIFY                                           1
FAILURE TO UPLOAD PHOTO                                                             1
REPAIRS, FAIL TO MAKE REQUIRED ENTRIES REGARDING                                    1
EMPLOYER ALLOW FEMALE EMPLOYEE TOPLESS & NOT ON STAGE                               1
TOPLESS FEMALE EMPLOYEE NOT ON STAGE                                                1
BICYCLE NO BELL                                                                     1
DISCOURTEOUS TO PASSENGER                                                           1
ALLOW CONSUMPTION BETWEEN 4:00 AM - 12 NOON (SUNDAY ONLY)                           1
TRANSFER WITHOUT PERMISSION                                                         1
RECEPTACLES; REMOVING FROM STREET AFTER GARBAGE COLLECTION (MUST BE COLLECTED BE    1
ANIMAL/DOG IN PARK BUILDING/BATH FACILITY                                           1
MORE THAN ONE; APPLY FOR/ACCEPT WITHOUT WRITTEN PERMISSION                          1
ACCIDENT WITH INJURY/DAMAGE; FAIL TO STOP AND FULLY IDENTIFY                        1
DRIVE THRU BARRIER                                                                  1
NO PARKING (STREET CLEANING)                                                        1
METER (BROKEN)                                                                      1
BICYCLE NO LIGHTS                                                                   1

In [49]:
# -------------------------------------
# Q5) Count of summons by gender
# -------------------------------------
summons_by_gender = (
    df["SEX_CLEAN"]
    .value_counts()
    .rename(index={"M": "Male", "F": "Female"})
)

print(
    f"\nQ5: Summons by gender — "
    + ", ".join(f"{g}: {c:,}" for g, c in summons_by_gender.items())
)

Q5: Summons by gender — Male: 1,013,591, Female: 130,370

In [50]:
# --------------------------------------------
# Q6) How many summons were issued by race?
# --------------------------------------------
summons_by_race = df["RACE_CLEAN"].value_counts().rename("summons_count")

top_race = summons_by_race.idxmax()
top_race_count = summons_by_race.max()

print(
    f"\nQ6: {summons_by_race.sum():,} summons had a recorded race. "
    f"The most common was {top_race} with {top_race_count:,} summons.\n"
    f"{summons_by_race.to_string()}"
)

Q6: 724,524 summons had a recorded race. The most common was BLACK with 316,676 summons.
RACE_CLEAN
BLACK                             316676
WHITE HISPANIC                    192409
WHITE                              87448
BLACK HISPANIC                     70375
ASIAN / PACIFIC ISLANDER           49862
AMERICAN INDIAN/ALASKAN NATIVE      5735
OTHER                               2019

In [51]:
# ------------------------------------------------------------------------
# Q7) Which borough had the fewest offenses per 100K people?
# ------------------------------------------------------------------------
borough_population = pd.Series({
    "BRONX":         1_472_654,
    "BROOKLYN":      2_736_074,
    "MANHATTAN":     1_694_251,
    "QUEENS":        2_405_464,
    "STATEN ISLAND":   495_747,
}, name="population")

rates_df = (
    df["BORO_CLEAN"]
    .value_counts()
    .rename("summons_count")
    .to_frame()
    .join(borough_population)
    .assign(offenses_per_100k=lambda x: (x["summons_count"] / x["population"]) * 100_000)
    .sort_values("offenses_per_100k")
)

fewest_boro  = rates_df.index[0]
fewest_rate  = rates_df["offenses_per_100k"].iloc[0]
highest_boro = rates_df.index[-1]
highest_rate = rates_df["offenses_per_100k"].iloc[-1]

print(
    f"\nQ7: {fewest_boro} had the fewest offenses per 100K residents ({fewest_rate:.2f}), "
    f"while {highest_boro} had the highest ({highest_rate:.2f}).\n"
    f"{rates_df.to_string()}"
)

Q7: STATEN ISLAND had the fewest offenses per 100K residents (9445.14), while NEW YORK had the highest (nan).
               summons_count  population  offenses_per_100k
BORO_CLEAN
STATEN ISLAND          46824    495747.0        9445.140364
QUEENS                246314   2405464.0       10239.770789
BROOKLYN              427679   2736074.0       15631.119626
MANHATTAN             275884   1694251.0       16283.537681
BRONX                 312327   1472654.0       21208.444074
NEW YORK               63056         NaN                NaN

In [52]:
## Q1 
print(f"Q1: {top_borough} had the most summons with {top_count:,} total.")

## Q2 
print(
    f"\nQ2: The top 10 most common offenses occurred {top_10_total:,} times combined. "
    f"The #1 offense was '{top_offense}' with {top_offense_count:,} occurrences.\n"
    f"{top_10_offenses.to_string()}"
)

## Q3 
print(
    f"\nQ3: {summons_by_year.sum():,} total summons were issued. "
    f"The peak year was {peak_year} with {peak_count:,} summons.\n"
    f"{summons_by_year.to_string()}"
)


## Q4

print(
    f"\nQ4: {len(singletons)} offense(s) appeared exactly once (rarest). "
    f"{len(very_rare)} offense(s) had 2 or fewer occurrences.\n"
    f"Singleton offenses:\n{singletons.to_string()}"
)

## Q5 

print(
    f"\nQ5: Summons by gender — "
    + ", ".join(f"{g}: {c:,}" for g, c in summons_by_gender.items())
)


## Q6

print(
    f"\nQ6: {summons_by_race.sum():,} summons had a recorded race. "
    f"The most common was {top_race} with {top_race_count:,} summons.\n"
    f"{summons_by_race.to_string()}"
)

## Q7

print(
    f"\nQ7: {fewest_boro} had the fewest offenses per 100K residents ({fewest_rate:.2f}), "
    f"while {highest_boro} had the highest ({highest_rate:.2f}).\n"
    f"{rates_df.to_string()}"
)

Q1: BROOKLYN had the most summons with 427,679 total.

Q2: The top 10 most common offenses occurred 764,799 times combined. The #1 offense was 'CONSUMPTION OF ALCOHOL' with 248,650 occurrences.
OFFENSE_DESCRIPTION
CONSUMPTION OF ALCOHOL           248650
FEDERAL MOTOR VEH. SAFETY REG    158420
MARIJUANA, POSSESSION OF          84910
URINATING IN PUBLIC               50340
RECKLESS DRIVING                  44691
ALCOHOLIC BEVERAGE IN PUBLIC      43789
FAILURE TO COMPLY WITH SIGN       42810
TRESPASS                          38595
OTHER ADMIN CODE                  31851
DISORDERLY CONDUCT                20743

Q3: 1,384,334 total summons were issued. The peak year was 2015 with 297,748 summons.
YEAR
2015    297748
2016    267950
2017    165093
2018     89895
2019     85899
2020     55589
2021     45717
2022     58059
2023    106529
2024     94542
2025    117313

Q4: 52 offense(s) appeared exactly once (rarest). 79 offense(s) had 2 or fewer occurrences.
Singleton offenses:
OFFENSE_DESCRIPTION
RAILROAD TRACK, PLACE LESS THAN 5 FEET FROM                                         1
UNLICENSED HAIR/NAIL SALON                                                          1
HARASS/THREATEN/ABUSE; PASSENGER                                                    1
STREET; PLACE/PERMIT WITHOUT A PERMIT                                               1
VEHICLE REBUILDER FAILED TO KEEP PROPER RECORDS                                     1
DANGEROUS CONDITION; CREATE IN PARK/ROAD                                            1
DEFECTIVE DURING TRIP; FAIL TO NOTIFY PASSENGER                                     1
DENIAL OF LICENSE OR RENEWAL, SUSPENSION AND REVOCATION                             1
SKATEBOARD; OTHER THAN DESIGNATED AREA                                              1
SPRAY PAINT/BROAD TIPPED MARKER ON DISPLAY (NOT IN A LOCKED CASE)                   1
DISTRIBUTOR (TO VENDOR), UNLICENSED                                                 1
AUDIO EQUIPMENT; FAIL TO OBLIGE PASSENGER REGARDING ON/OFF/SELECTION                1
BICYCLE ON GRASS/BRIDLE PATH; RIDE ON                                               1
UNREASONABLE NOISE (FROM A MUSICAL INSTRUMENT)                                      1
SOLICIT PASSENGER; BY USE OF ANOTHER PERSON                                         1
COMMUNICATION SYSTEM, BASE; UNLICENSED                                              1
NO ""NO CHOKING"" SIGN IN FOOD ESTABLISHMENT                                        1
NO ""BILLIARD & POCKET-BILLIARD ROOM LICENSE""                                      1
UNLICENSED LOCKSMITH/KEY MAKER                                                      1
UNVACCINATED DOG                                                                    1
NO ""CERTIFICATE OF OCCUPANCY""                                                     1
NO WASHING FACILITY WITH RUNNING HOT OR COLD WATER                                  1
DRIVER DOES NOT POSSESS ""FOR HIRE-VEHICLE"" LICENSE                                1
UNLICENSED SIDEWALK CAF                                                             1
SOLICIT PASSENGER; WORDS OTHER THAN "TAXI", "CAB", OR "TAXICAB"                     1
VEHICLE DISMANTLER FAILED TO KEEP PROPER RECORDS                                    1
CART MAN, UNLICENSED                                                                1
NO SANITARY SOAP DISPENSER                                                          1
FAILURE TO NOTIFY A PRECINCT WITHIN 2 HOURS OF TOWING A VEHICLE WHEN OWNER IS UN    1
SALE BETWEEN 3AM-12PM ON SUNDAY                                                     1
DEFECTIVE; PICK-UP/TRANSPORT PASSENGERS WHEN                                        1
METER OPERATING; TAMPER WITH METER/SEALS/CONNECTION/WIRING/TIRES TO AFFECT          1
UNHYGIENIC USE OF THE FOUNTAIN OR POOL AREA                                         1
USED PAPER TOWELS/PAPER/OTHER MATERIALS NOT IN GARBAGE                              1
LOST/STOLEN; FAIL TO NOTIFY WITHIN 72 HOURS                                         1
OPENING ENTRIES; FAIL TO SIGN AND CERTIFY                                           1
FAILURE TO UPLOAD PHOTO                                                             1
REPAIRS, FAIL TO MAKE REQUIRED ENTRIES REGARDING                                    1
EMPLOYER ALLOW FEMALE EMPLOYEE TOPLESS & NOT ON STAGE                               1
TOPLESS FEMALE EMPLOYEE NOT ON STAGE                                                1
BICYCLE NO BELL                                                                     1
DISCOURTEOUS TO PASSENGER                                                           1
ALLOW CONSUMPTION BETWEEN 4:00 AM - 12 NOON (SUNDAY ONLY)                           1
TRANSFER WITHOUT PERMISSION                                                         1
RECEPTACLES; REMOVING FROM STREET AFTER GARBAGE COLLECTION (MUST BE COLLECTED BE    1
ANIMAL/DOG IN PARK BUILDING/BATH FACILITY                                           1
MORE THAN ONE; APPLY FOR/ACCEPT WITHOUT WRITTEN PERMISSION                          1
ACCIDENT WITH INJURY/DAMAGE; FAIL TO STOP AND FULLY IDENTIFY                        1
DRIVE THRU BARRIER                                                                  1
NO PARKING (STREET CLEANING)                                                        1
METER (BROKEN)                                                                      1
BICYCLE NO LIGHTS                                                                   1

Q5: Summons by gender — Male: 1,013,591, Female: 130,370

Q6: 724,524 summons had a recorded race. The most common was BLACK with 316,676 summons.
RACE_CLEAN
BLACK                             316676
WHITE HISPANIC                    192409
WHITE                              87448
BLACK HISPANIC                     70375
ASIAN / PACIFIC ISLANDER           49862
AMERICAN INDIAN/ALASKAN NATIVE      5735
OTHER                               2019

Q7: STATEN ISLAND had the fewest offenses per 100K residents (9445.14), while NEW YORK had the highest (nan).
               summons_count  population  offenses_per_100k
BORO_CLEAN
STATEN ISLAND          46824    495747.0        9445.140364
QUEENS                246314   2405464.0       10239.770789
BROOKLYN              427679   2736074.0       15631.119626
MANHATTAN             275884   1694251.0       16283.537681
BRONX                 312327   1472654.0       21208.444074
NEW YORK               63056         NaN                NaN

In [1]:
## I felt like it was pretty simple to use CoPilot to complete this task but it did try and take a lot of liberties with my code, like telling me to download numpys, which was unhelpful.

## I also had to ask it to format the output in ways that I wanted, but that meant it would go back and rewrite the code for earlier questions, which I didn’t ask for, and that’s something that I wish I had been more explicit. 

## Overall I think it was succesful in helping me get me the results that I want but I probably would have formatted the output differently